### ISSUE TITLE
FALCON-X: No Change-points found despite obvious major copy number alterations

### ISSUE THREAD

**Issue by SRHilz** [yuchaojiang/MARATHON#1]
Hello,

I am looking forward to trying out your new pipeline to see if it can be incorporated into my tumor clonality work. 

However, I am getting stuck on getting change points to be properly called from FALCON-X, and wanted to ask if, for the problem I am having, you could please point me in the right direction for what I could be doing wrong?

**The issue:** Samples with very clear, well-characterized copy number changes (such as heterozygous loss of 19q, which is known to be a characteristic of the samples I am working with and which is called with other CN tools such as Sequenza), are not having any change points called with FALCON-X. 

**Details:** After getting each step of FALCON-X to execute without error (I had first run through your demo code for chr17 to ensure everything was reproducible on my machine - it was), I can produce a final chr19 plot for a sample with known chr19q heterozygous loss in which chr19q LoH (see A freq panel) and even a difference in coverage between the p and q arms is clear (see Relative Coverage panel), but no change points are detected (tauhat = NULL; see Allele-specific CN panel):

<img width="551" alt="screen shot 2018-07-18 at 3 50 44 pm" src="https://user-images.githubusercontent.com/5839184/42912084-6e57f71c-8aa2-11e8-9ce9-d3811bad6947.png">

This is prior to any filtering, which cannot be performed anyways since no change points are identified.

**Question:** Is there an obvious common error users make in generating their input or running the code that would cause this to happen? I am at a loss for even knowing exactly where to begin with troubleshooting.

My FALCON-X run code (adapted from your demo code) is attached (includes descriptions + views of each input file I am using), and I am happy to provide any other info that would be helpful.

[falconx_real.txt](https://github.com/yuchaojiang/MARATHON/files/2207731/falconx_real.txt)

Thank you so much!

**Comment by yuchaojiang** [comment]
Hi Stephanie,

I am copying Hao here, who is the author for Falcon-X.

Hao, it seems that Falcon-X didn’t pick up the LOH on the p-arm even before QC. Could you please help with troubleshooting? Let me know if there’s anything I can help with.

Thanks!
Yuchao

On Jul 18, 2018, at 8:16 PM, Stephanie Hilz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am looking forward to trying out your new pipeline to see if it can be incorporated into my tumor clonality work.

However, I am getting stuck on getting change points to be properly called from FALCON-X, and wanted to ask if, for the problem I am having, you could please point me in the right direction for what I could be doing wrong?

The issue: Samples with very clear, well-characterized copy number changes (such as heterozygous loss of 19q, which is known to be a characteristic of the samples I am working with and which is called with other CN tools such as Sequenza), are not having any change points called with FALCON-X.

Details: After getting each step of FALCON-X to execute without error (I had first run through your demo code for chr17 to ensure everything was reproducible on my machine - it was), I can produce a final chr19 plot for a sample with known chr19q heterozygous loss in which chr19q LoH (see A freq panel) and even a difference in coverage between the p and q arms is clear (see Relative Coverage panel), but no change points are detected (tauhat = NULL; see Allele-specific CN panel):

[screen shot 2018-07-18 at 3 50 44 pm]<https://user-images.githubusercontent.com/5839184/42912084-6e57f71c-8aa2-11e8-9ce9-d3811bad6947.png>

This is prior to any filtering, which cannot be performed anyways since no change points are identified.

Question: Is there an obvious common error users make in generating their input or running the code that would cause this to happen? I am at a loss for even knowing exactly where to begin with troubleshooting.

My FALCON-X run code (adapted from your demo code) is attached (includes descriptions + views of each input file I am using), and I am happy to provide any other info that would be helpful.

falconx_real.txt<https://github.com/yuchaojiang/MARATHON/files/2207731/falconx_real.txt>

Thank you so much!

**Comment by yuchaojiang** [comment]
Hi Yuchao and Stephanie,

I have a few deadlines to hit this week and will try to look into this one
next week.

Hao

**Comment by SRHilz** [comment]
Wonderful, thank you, Hao!

**Comment by SRHilz** [comment]
Hi Hao,

I wanted to follow up to see if you might have had a chance to look at it yet? Thank you!

Stephanie

**Comment by haochen6** [comment]
Hi Stephanie,

Sorry for getting back late.  As it is difficult to troubleshoot from the R
code only, I am wondering if it is possible that you also provide the data
so I can try to run through to see what happens.

Best,
Hao

**Comment by SRHilz** [comment]
Thank you very much for offering to look, and sorry in return for the delay on my end. I had to discuss with a mentor the best way to go about sharing some example data in a secure manner, and I think we have come up with something that will work. I am following up right now via email. Thank you!

**Comment by SRHilz** [comment]
Hi Hao,

I wanted to see if you received my email and if the data I was going to share was the correct kind you needed to troubleshoot? Thanks!

Stephanie

**Comment by SRHilz** [comment]
Thank you so much, Hao, for helping me solve the problem. 

For any other users who might encounter this problem: 

It turned out that I needed to first sort my matrix of allelic read depth and genotypes by loci (position) along each chromosome prior to identifying change points with getChangepoints.x.

Here is an example snippet of code Hao provided to give a bit more context and an example of how/when to do this:

```{r}
library(falconx)
mydata0 = read.table("Patient100_chr17_het.txt", header=T)
temp = sort(mydata0[,2], decreasing=F, index.return=T)
mydata = mydata[temp$ix,]
tauhat = getChangepoints.x(mydata[,7:10], mydata[,11:12])
cn = getASCN.x(mydata[,7:10], mydata[,11:12], tauhat=tauhat)
view(cn)
```

Thank you very much again!
