### ISSUE TITLE
Failing to install in R 4.1.0

### ISSUE THREAD

**Issue by teacakedeadlift** [yuchaojiang/MARATHON#5]
Novice user here. I can't get CODEX2 to install and therefore MARATHON won't install on my Mac.

macOS catalina 10.15.7 
R 4.1.0
Bioconductor 3.13

The error appears to be something to do with IRanges namespace:

'Error: object ‘RangesList’ is not exported by 'namespace:IRanges'
Execution halted
ERROR: lazy loading failed for package ‘CODEX2’'

I've managed to get it to install on R 4.0.5 Bioconductor 3.12 in a conda env.

It's unclear whether this is because RangesList() is deprecated in IRanges 2.26.0 which is the version in Bioconductor 3.13 (as per [here](http://bioconductor.org/news/bioc_3_13_release/)).

Any help appreciated.

**Comment by yuchaojiang** [comment]
Were you able to successfully install the package IRanges?

On Jul 4, 2021, at 9:52 AM, teacakedeadlift ***@***.******@***.***>> wrote:



Novice user here. I can't get CODEX2 to install and therefore MARATHON won't install on my Mac.

macOS catalina 10.15.7
R 4.1.0
Bioconductor 3.13

The error appears to be something to do with IRanges namespace:

'Error: object ‘RangesList’ is not exported by 'namespace:IRanges'
Execution halted
ERROR: lazy loading failed for package ‘CODEX2’'

I've managed to get it to install on R 4.0.5 Bioconductor 3.12 in a conda env.

It's unclear whether this is because RangesList() is deprecated in IRanges 2.26.0 which is the version in Bioconductor 3.13 (as per here<http://bioconductor.org/news/bioc_3_13_release/>).

Any help appreciated.

**Comment by teacakedeadlift** [comment]
Yes, IRanges 2.26.0 is installed.

When I run devtools::install_github("yuchaojiang/CODEX2/package”) I notice I get the message
"Skipping 7 packages not available: GenomeInfoDb, Biostrings, IRanges, S4Vectors, BSgenome.Hsapiens.UCSC.hg19, GenomicRanges, Rsamtools"
Unclear if this is related or not. All these packages are installed.

Note I am using RStudio Version 1.4.1717.

Output from BiocManager::valid() is TRUE

**Comment by paulemnah** [comment]
Hello. I have been trying to install the packages, and am facing the exact same problem as teacakedeadlift. Has a solution been found for this? 

Additionally, I tried to install the docker image. But after I do, it asks me for a username and password for logging into Rstudio. What is this password? 

Thanks for your help!


> Novice user here. I can't get CODEX2 to install and therefore MARATHON won't install on my Mac.
> 
> macOS catalina 10.15.7
> R 4.1.0
> Bioconductor 3.13
> 
> The error appears to be something to do with IRanges namespace:
> 
> 'Error: object ‘RangesList’ is not exported by 'namespace:IRanges'
> Execution halted
> ERROR: lazy loading failed for package ‘CODEX2’'
> 
> I've managed to get it to install on R 4.0.5 Bioconductor 3.12 in a conda env.
> 
> It's unclear whether this is because RangesList() is deprecated in IRanges 2.26.0 which is the version in Bioconductor 3.13 (as per [here](http://bioconductor.org/news/bioc_3_13_release/)).
> 
> Any help appreciated.

**Comment by yuchaojiang** [comment]
The function RangesList() by IRanges is deprecated, leading to the error.
I've made the updates. Please try again.
