### ISSUE TITLE
Can  FALCON-X be used on mice WES? 

### ISSUE THREAD

**Issue by ruhollah2** [yuchaojiang/MARATHON#6]
Hi there!

I am wondering how one should use your R package FALCON-X on **_mice WES data_** to infer the allele-specific copy number alteration?

In fact, my original intention is to use your R package [Canopy](https://github.com/yuchaojiang/Canopy) to find the **_intra-tumor heterogeneity_** in our mice tumors. But then, as per your instruction in "[How do I generate SNA and CNA input for Canopy?](https://github.com/yuchaojiang/Canopy/blob/master/instruction/SNA_CNA_input.md)" I came across FALCON-X as a pre-requisite to Canopy.

Looking forward to hearing from you soon!

**Comment by yuchaojiang** [comment]
Yes you can use FALCON-X for the mouse genome. You just need to call the heterozygous SNPs from the mouse instead of from the human.

On Dec 5, 2022, at 10:43 PM, Ruhollah Moussavi-Baygi ***@***.******@***.***>> wrote:



Hi there!

I am wondering how one should use your R package FALCON-X on mice WES data to infer the allele-specific copy number alteration?

In fact, my original intention is to use your R package Canopy<https://github.com/yuchaojiang/Canopy> to find the intra-tumor heterogeneity in our mice tumors. But then, as per your instruction in "How do I generate SNA and CNA input for Canopy?<https://github.com/yuchaojiang/Canopy/blob/master/instruction/SNA_CNA_input.md>" I came across FALCON-X as a pre-requisite to Canopy.

Looking forward to hearing from you soon!
